Feature booking
ida-dar/project-pizzeria pull request #1
Opened 2021-05-13 15:16 UTC by ida-dar

2021-05-16 22:10 UTC, michal-bootcamp requested changes

2021-05-16 22:10 UTC, michal-bootcamp commented on src/js/components/DatePicker.js
> +        firstDayOfWeek: 1
przerzuciłbym tę jedynkę do settingsów

2021-05-17 14:25 UTC, ida-dar commented on src/js/components/DatePicker.js
> +        firstDayOfWeek: 1
Po przerzuceniu do settingsów w konsoli wyświetlił się błąd: _flatpickr: invalid locale 1_, dlatego zostawiłam bez zmian

2021-05-17 14:42 UTC, michal-bootcamp approved these changes

2021-05-17 15:21 UTC, merged